[package]
name = "enigma"
version = "0.1.0"
authors = ["Kristian Zarebski <krizar312@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
log = "0.4.0"
env_logger = "0.9.0"
test-log = "0.2.8"